export let ssb64 = {
    "Bowser": ["Default", "Black", "Blue", "Green", "Red", "Yellow"],
    "Conker": ["Default", "Black", "Green", "Pink", "Red", "White"],
    "Dark Samus": ["Default", "Brown", "Gray", "Power", "Purple", "White"],
    "DonkeyKong": ["Default", "Black", "Blue", "Green", "Pink", "Red", "White", "Yellow"],
    "Dr. Mario": ["Default", "Black", "Blue", "Green", "Pink", "Yellow"],
    "Falco": ["Default", "Gray", "Green", "Red", "White", "Yellow"],
    "Falcon": ["Default", "Black", "Blood", "Blue", "Gold", "Green", "Pink", "Red"],
    "Fox": ["Default", "Black", "Blue", "Green", "Orange", "Purple"],
    "Ganondorf": ["Default", "Blue Skin", "Green", "Purple Skin", "Purple", "Red"],
    "Jigglypuff": ["Default", "Blue", "Green Bow Light Skin", "Green", "Monochrome", "Purple", "Red", "Yellow"],
    "King Dedede": ["Default", "Black", "Blue", "Brown", "Green", "Purple"],
    "Kirby": ["Default", "Blue", "Green", "Meta Knight", "Monochrome", "Red", "Yellow"],
    "Link": ["Default", "Black", "Blue", "Red", "White", "Yellow"],
    "Lucas": ["Default", "Brown Shorts", "Claus", "Green Shorts", "Kumatora", "Pink Shorts"],
    "Luigi": ["Default", "Blue", "Fire", "Pink", "Super Show", "Waluigi"],
    "Marina": ["Default", "Blue", "Green", "Purple", "Red", "Yellow"],
    "Mario": ["Default", "Blue", "Brown", "Classic", "Fire", "Green", "Wario"],
    "Marth": ["Default", "Black", "Gold", "Green", "Red", "White"],
    "Mewtwo": ["Default", "Blue", "Cyan", "Green", "Red", "Yellow"],
    "Ness": ["Default", "Blue", "Green", "Purple", "White", "Yellow"],
    "Pikachu": ["Default", "All Green", "Blue", "Green", "Purple", "Red", "Yellow"],
    "Samus": ["Default", "Black", "Green", "Pink", "Power", "Purple", "White"],
    "Sheik": ["Default", "Black", "Green", "Purple", "Red Blue", "Red"],
    "Sonic": ["Default", "Black", "Green", "Purple", "Red", "Yellow", "Classic Default", "Classic Green", "Classic Orange", "Classic Pink", "Classic Red", "Classic Yellow"],
    "Wario": ["Default", "Blue", "Green", "Mario", "Purple", "Yellow"],
    "Wolf": ["Default", "Black", "Blue", "Green", "Pink", "Purple"],
    "Yoshi": ["Default", "Black", "Blue", "Dark Blue", "Pink", "Red", "White", "Yellow"],
    "Young Link": ["Default", "Blue", "Cyan", "Dark", "Pink Hair", "Red"],
};

export let ssbm = {
    'Bowser': ['Default', 'Black', 'Blue', 'Red'], 
    'DonkeyKong': ['Default', 'Black', 'Blue', 'Green', 'Red'], 
    'DrMario': ['Default', 'Black', 'Blue', 'Green', 'Red'], 
    'Falco': ['Default', 'Green', 'Red', 'White'], 
    'Falcon': ['Default', 'Black', 'Blood', 'Blue', 'Green', 'Pink'], 
    'Fox': ['Default', 'Blue', 'Green', 'Orange'], 
    'Ganondorf': ['Default', 'Blue', 'Green', 'Purple', 'Red'], 
    'IceClimbers': ['Default', 'Green', 'Nana Orange', 'Nana Purple'], 
    'Jigglypuff': ['Default', 'Blue', 'Crown', 'Green', 'Red'], 
    'Kirby': ['Default', 'Blue', 'Green', 'Red', 'White', 'Yellow'], 
    'Link': ['Default', 'Black', 'Blue', 'Red', 'White'], 
    'Luigi': ['Default', 'Blue', 'Fire', 'Pink'], 
    'Mario': ['Default', 'Black', 'Blue', 'Green', 'Wario'], 
    'Marth': ['Default', 'Black', 'Green', 'Red', 'White'], 
    'Mewtwo': ['Default', 'Blue', 'Green', 'Red'], 
    'MrGameAndWatch': ['Default', 'Blue', 'Green', 'Red'], 
    'Ness': ['Default', 'Blue', 'Green', 'Yellow'], 
    'Peach': ['Default', 'Blue', 'Daisy', 'Green', 'White'], 
    'Pichu': ['Default', 'Blue', 'Green', 'Red'], 
    'Pikachu': ['Default', 'Blue', 'Green', 'Red'], 
    'Roy': ['Default', 'Blue', 'Green', 'Orange', 'Red'], 
    'Samus': ['Default', 'Black', 'Green', 'Pink', 'Purple'], 
    'Sheik': ['Default', 'Black', 'Blue', 'Green', 'Red'], 
    'Yoshi': ['Default', 'Cyan', 'Dark Blue', 'Pink', 'Red', 'Yellow'], 
    'YoungLink': ['Default', 'Black', 'Blue', 'Red', 'White'], 
    'Zelda': ['Default', 'Blue', 'Green', 'Red', 'White']
};

export let ssbult = {
    "Banjo&Kazooie": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Pink",
        "Red",
        "White",
        "Yellow"
    ],
    "Bayonetta": [
        "Default",
        "Bayo 1 Default",
        "Blue",
        "Green",
        "Jeanne",
        "Pink",
        "White",
        "Yellow"
    ],
    "Bowser": [
        "Default",
        "Black",
        "Blue",
        "Gray",
        "Green",
        "Orange",
        "Red",
        "Yellow"
    ],
    "BowserJr": [
        "Default",
        "Iggy",
        "Larry",
        "Lemmy",
        "Ludwig",
        "Morton",
        "Roy",
        "Wendy"
    ],
    "Byleth": [
        "Default",
        "Default Female",
        "Female Gray",
        "Female Green",
        "Female Red",
        "Male Black",
        "Male Blue",
        "Male Yellow"
    ],
    "Chrom": [
        "Default",
        "Black",
        "Cyan",
        "Green",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Cloud": [
        "Default",
        "Advent Black",
        "Advent Blue",
        "Advent Purple",
        "Blue",
        "Brown",
        "Default Advent",
        "Red"
    ],
    "Corrin": [
        "Default",
        "Default Female",
        "Female Black",
        "Female Orange",
        "Female Pink",
        "Male Blue",
        "Male Green",
        "Male Red"
    ],
    "Daisy": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Pink",
        "Purple",
        "Red",
        "White"
    ],
    "DarkPit": [
        "Default",
        "Blue",
        "Brown",
        "Green",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "DarkSamus": [
        "Default",
        "Black",
        "Gray",
        "Green",
        "Pink",
        "Purple",
        "Red",
        "Yellow"
    ],
    "DiddyKong": [
        "Default",
        "Blue",
        "Cyan",
        "Green",
        "Pink",
        "Purple",
        "White",
        "Yellow"
    ],
    "DonkeyKong": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Pink",
        "Red",
        "White",
        "Yellow"
    ],
    "DrMario": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Pink",
        "Purple",
        "Red",
        "Yellow"
    ],
    "DuckHunt": [
        "Default",
        "Black",
        "Blue",
        "Brown",
        "Red",
        "Tan",
        "White",
        "Yellow"
    ],
    "Falco": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Orange",
        "Pink",
        "Red",
        "White"
    ],
    "Falcon": [
        "Default",
        "Black",
        "Blood",
        "Blue",
        "Cyan",
        "Gold",
        "Green",
        "Pink"
    ],
    "Fox": [
        "Default",
        "Black",
        "Green",
        "Orange",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Ganondorf": [
        "Default",
        "Blue",
        "Brown",
        "Gray",
        "Green",
        "Purple",
        "Violet",
        "White"
    ],
    "Greninja": [
        "Default",
        "Black",
        "Gray",
        "Green",
        "Pink",
        "Purple",
        "Red",
        "Violet"
    ],
    "Hero": [
        "Default",
        "Eight Blue",
        "Eight",
        "Erdrick White",
        "Erdrick",
        "Red",
        "Solo Orange",
        "Solo"
    ],
    "IceClimbers": [
        "Default",
        "Blue",
        "Green",
        "Indigo",
        "Nana Brown",
        "Nana Orange",
        "Nana Red",
        "Nana White"
    ],
    "Ike": [
        "Default",
        "Black",
        "Blue",
        "Brown",
        "Green",
        "Purple",
        "Red",
        "Yellow"
    ],
    "Incineroar": [
        "Default",
        "Black",
        "Blue",
        "Gray",
        "Green",
        "Orange",
        "Purple",
        "White"
    ],
    "Inkling": [
        "Default",
        "Default Male",
        "Female Pink",
        "Female Purple",
        "Female Yellow",
        "Male Cyan",
        "Male Green",
        "Male Indigo"
    ],
    "Isabelle": [
        "Default",
        "Blue",
        "Gray",
        "Pink",
        "Purple",
        "Red",
        "Teal",
        "Yellow"
    ],
    "Jigglypuff": [
        "Default",
        "Bow",
        "Bug Catcher Hat",
        "Leaf Hat",
        "Nurse Hat",
        "Red",
        "Serena Hat",
        "Sleep Hat"
    ],
    "Joker": [
        "Default",
        "Blue",
        "Purple",
        "Red",
        "School White",
        "School",
        "White",
        "Yellow"
    ],
    "Kazuya": [
        "Default",
        "Black",
        "Blue",
        "Red",
        "Suit Purple",
        "Suit White",
        "Suit Yellow",
        "Suit"
    ],
    "Ken": [
        "Default",
        "Black",
        "Blue",
        "Cyan",
        "Gray",
        "Green",
        "White",
        "Yellow"
    ],
    "KingDedede": [
        "Default",
        "Black",
        "Blue",
        "Cyan",
        "Gray",
        "Green",
        "Pink",
        "Purple"
    ],
    "KingK.Rool": [
        "Default",
        "Black",
        "Blue",
        "Brown",
        "Orange",
        "Pink",
        "White",
        "Yellow"
    ],
    "Kirby": [
        "Default",
        "Blue",
        "Green",
        "Orange",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Link": [
        "Default",
        "Dark",
        "Fierce Deity",
        "Green",
        "Indigo",
        "Red",
        "Teal",
        "White"
    ],
    "LittleMac": [
        "Default",
        "Black",
        "Blue",
        "Hoodie",
        "White",
        "Wireframe Hoodie",
        "Wireframe",
        "Yellow"
    ],
    "Lucario": [
        "Default",
        "Gray",
        "Green",
        "Navy",
        "Pink",
        "Purple",
        "Teal",
        "White"
    ],
    "Lucas": [
        "Default",
        "Blue",
        "Claus",
        "Duster",
        "Green",
        "Masked Man",
        "Purple",
        "Red"
    ],
    "Lucina": [
        "Default",
        "Black",
        "Green",
        "Navy",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Luigi": [
        "Default",
        "Blue",
        "Cyan",
        "Fire",
        "Orange",
        "Pink",
        "Purple",
        "Yellow"
    ],
    "Mario": [
        "Default",
        "Black",
        "Blue",
        "Builder",
        "Green",
        "USA",
        "Waluigi",
        "Wedding"
    ],
    "Marth": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "MegaMan": [
        "Default",
        "Brown",
        "Cyan",
        "Gray",
        "Green",
        "Melon",
        "Orange",
        "Red"
    ],
    "MetaKnight": [
        "Default",
        "Dark",
        "Galacta",
        "Green",
        "Navy",
        "Pink",
        "Red",
        "White"
    ],
    "Mewtwo": [
        "Default",
        "Blue",
        "Brown",
        "Cyan",
        "Orange",
        "Pink",
        "Shadow",
        "Yellow"
    ],
    "MiiBrawler": [
        "Default",
    ],
    "MiiGunner": [
        "Default",
        "Sans",
        "Cuphead",
        "Vault Boy"
    ],
    "MiiSwordfighter": [
        "Default"
    ],
    "MinMin": [
        "Default",
        "Black",
        "Blue",
        "Cyan",
        "Green",
        "Pink",
        "Red",
        "Yellow"
    ],
    "MrGameAndWatch": [
        "Default",
        "Blue",
        "Cyan",
        "Green",
        "Red",
        "Teal",
        "White",
        "Yellow"
    ],
    "Ness": [
        "Default",
        "Black",
        "Blue",
        "Cyan",
        "Green",
        "Purple",
        "White",
        "Yellow"
    ],
    "Olimar": [
        "Default",
        "Alph Green",
        "Alph Pink",
        "Alph Red",
        "Alph",
        "Blue",
        "Green",
        "Red"
    ],
    "PacMan": [
        "Default",
        "Black",
        "Blue",
        "Oven Mitts",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Palutena": [
        "Default",
        "Black",
        "Blue",
        "Cyan",
        "Green",
        "Pink",
        "Purple",
        "Red"
    ],
    "Peach": [
        "Default",
        "Black",
        "Blue",
        "Fire",
        "Green",
        "Red",
        "White",
        "Yellow"
    ],
    "Pichu": [
        "Default",
        "Aqua",
        "Flower",
        "Focus Band",
        "Goggles",
        "Red",
        "Skull",
        "Spiky"
    ],
    "Pikachu": [
        "Default",
        "Blue",
        "Glasses",
        "Green",
        "Libre",
        "Red",
        "Selene Cap",
        "Yellow"
    ],
    "PiranhaPlant": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Pink",
        "Purple",
        "White",
        "Yellow"
    ],
    "Pit": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Pink",
        "Red",
        "White",
        "Yellow"
    ],
    "PokemonTrainer": [
        "Default",
        "Calem",
        "Default Female",
        "Ethan",
        "Hilda",
        "Lucas",
        "May",
        "Selene"
    ],
    "PyraMythra": [
        "Default",
        "Black",
        "Blue",
        "Gormotti",
        "Green",
        "Metal",
        "Saturated",
        "Swapped"
    ],
    "Richter": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Ridley": [
        "Default",
        "Blue",
        "Gray",
        "Green",
        "Meta",
        "Purple",
        "Red",
        "Yellow"
    ],
    "ROB": [
        "Default",
        "Blue",
        "Cyan",
        "Famicom",
        "Green",
        "Purple",
        "Red",
        "Yellow"
    ],
    "Robin": [
        "Default",
        "Default Female",
        "Female Pink",
        "Female Red",
        "Female Yellow",
        "Male Blue",
        "Male Green",
        "Male White"
    ],
    "Rosalina": [
        "Default",
        "Black",
        "Green",
        "Pink",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Roy": [
        "Default",
        "Cyan",
        "Green",
        "Pink",
        "Purple",
        "Red",
        "Violet",
        "Yellow"
    ],
    "Ryu": [
        "Default",
        "Black",
        "Blue",
        "Cyan",
        "Gray",
        "Green",
        "Orange",
        "Purple"
    ],
    "Samus": [
        "Default",
        "Black",
        "Brown",
        "Fusion Suit",
        "Green",
        "Pink",
        "Purple",
        "White"
    ],
    "Sephiroth": [
        "Default",
        "Blue",
        "Coatless Violet",
        "Coatless",
        "Green",
        "Purple",
        "Red",
        "White"
    ],
    "Sheik": [
        "Default",
        "Black",
        "Green",
        "Indigo",
        "Purple",
        "Red",
        "White",
        "Yellow"
    ],
    "Shulk": [
        "Default",
        "Black",
        "Blue",
        "Lavender",
        "Orange",
        "Swimsuit",
        "White",
        "Yellow"
    ],
    "Simon": [
        "Default",
        "Black",
        "Blue",
        "Indigo",
        "Orange",
        "Purple",
        "Red",
        "Yellow"
    ],
    "Snake": [
        "Default",
        "Black",
        "Blue",
        "Camo",
        "Green",
        "Red",
        "White",
        "Yellow"
    ],
    "Sonic": [
        "Default",
        "Black",
        "Cyan",
        "Green",
        "Orange",
        "Purple",
        "White",
        "Yellow"
    ],
    "Sora": [
        "Default",
        "KH3D",
        "KHII",
        "KHIII",
        "Timeless River",
        "Ultimate Form",
        "Valor Form",
        "Wisdom Form"
    ],
    "Steve": [
        "Default",
        "Alex Blue",
        "Alex White",
        "Alex",
        "Enderman",
        "Steve Black",
        "Steve White",
        "Zombie"
    ],
    "Terry": [
        "Default",
        "Black",
        "Blue",
        "Brown",
        "Gray",
        "Green",
        "Orange",
        "Yellow"
    ],
    "ToonLink": [
        "Default",
        "Blue",
        "Brown",
        "Dark",
        "Gray",
        "Purple",
        "Red",
        "Teal"
    ],
    "Villager": [
        "Default",
        "Default Female",
        "Female Blue",
        "Female Green",
        "Female Yellow",
        "Male Cyan",
        "Male Purple",
        "Male Yellow"
    ],
    "Wario": [
        "Default",
        "Classic Cyan",
        "Classic Green",
        "Classic Red",
        "Classic",
        "Green",
        "Red",
        "Yellow"
    ],
    "WiiFit": [
        "Default",
        "Default Male",
        "Female Green",
        "Female Red",
        "Female Yellow",
        "Male Green",
        "Male Red",
        "Male Yellow"
    ],
    "Wolf": [
        "Default",
        "Black",
        "Blue",
        "Brown",
        "Green",
        "Orange",
        "Pink",
        "Red"
    ],
    "Yoshi": [
        "Default",
        "Blue",
        "Crafted",
        "Cyan",
        "Pink",
        "Purple",
        "Red",
        "Yellow"
    ],
    "YoungLink": [
        "Default",
        "Blue",
        "Cyan",
        "Dark",
        "Orange",
        "Pink",
        "Red",
        "White"
    ],
    "Zelda": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Purple",
        "Red",
        "Violet",
        "White"
    ],
    "ZeroSuitSamus": [
        "Default",
        "Black",
        "Blue",
        "Green",
        "Red",
        "Shorts Blue",
        "Shorts Orange",
        "White"
    ]
};

export let roa = {
    "Absa": [
        "Default",
        "Abyss",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "High Roller",
        "LoA",
        "Penguin",
        "Purple",
        "Ranked",
        "Red",
        "Steampunk",
        "Summer",
        "Twitch",
        "Valentines"
    ],
    "Clairen": [
        "Default",
        "Abyss",
        "Arcade 1",
        "Arcade 2",
        "Arcade 3",
        "Blue",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Genesis",
        "Golden",
        "Green",
        "Halloween",
        "Heat Wave",
        "Hero",
        "Infamous",
        "Orange",
        "Purple",
        "Ranked",
        "Summer",
        "Valentines",
        "White"
    ],
    "Elliana": [
        "Default",
        "Abyss",
        "Arcade 1",
        "Arcade 2",
        "Arcade 3",
        "Ayala",
        "Blue",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "Infamous",
        "On The Edge",
        "Pink",
        "Ranked",
        "Red",
        "Summer",
        "Valentines"
    ],
    "Etalus": [
        "Default",
        "Abyss",
        "Brown",
        "Champion",
        "Christmas",
        "Cyan",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Genesis",
        "Golden",
        "Green",
        "Halloween",
        "Panda",
        "Pink",
        "Pool Party",
        "Ranked",
        "Summer",
        "Valentines",
        "Yellow"
    ],
    "Forsburn": [
        "Default",
        "Abyss",
        "Blue",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Dreamscape",
        "Early Access",
        "Genesis",
        "Golden",
        "Green",
        "Halloween",
        "Heatwave",
        "Purple",
        "Ranked",
        "Red",
        "Summer",
        "Valentines",
        "White"
    ],
    "Hodan": [
        "Default",
        "Abyss",
        "Blue",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Green",
        "Grey",
        "Halloween",
        "Purple",
        "Ranked",
        "Red",
        "Summer",
        "Valentines"
    ],
    "Kragg": [
        "Default",
        "Abyss",
        "Blue",
        "Burrito",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Genesis",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "Pink",
        "Purple",
        "Ranked",
        "Summer",
        "Summit",
        "Valentines"
    ],
    "Maypul": [
        "Default",
        "Abyss",
        "Arcade Blue",
        "Arcade Green",
        "Arcade Pink",
        "Blue",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Golden",
        "GoTE",
        "Grey",
        "Halloween",
        "Panda",
        "Purple",
        "Ragnir",
        "Ranked",
        "Red",
        "Summer",
        "Valentines",
        "Yellow"
    ],
    "Mollo": [
        "Default",
        "Abyss",
        "Blue",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Green",
        "Halloween",
        "Pink",
        "Ranked",
        "Red",
        "Summer",
        "Valentines",
        "White"
    ],
    "Olympia": [
        "Default",
        "Abyss",
        "Blue",
        "Champion",
        "Christmas",
        "Dark Purple",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Green",
        "Halloween",
        "Ranked",
        "Red",
        "Summer",
        "Valentines",
        "White"
    ],
    "Orcane": [
        "Default",
        "Abyss",
        "Champion",
        "Christmas",
        "Cyan",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "Pool Party",
        "Purple",
        "Ranked",
        "Red",
        "Steampunk",
        "Summer",
        "Summit",
        "Valentines"
    ],
    "Ori": [
        "Default",
        "Abyss",
        "Champion",
        "Christmas",
        "Cyan",
        "Dark",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Green",
        "Halloween",
        "Infamous",
        "Pink",
        "Ranked",
        "Red",
        "Summer",
        "Valentines"
    ],
    "Pomme": [
        "Default",
        "Abyss",
        "Blue",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Green",
        "Halloween",
        "Purple",
        "Ranked",
        "Red",
        "Summer",
        "Valentines",
        "White"
    ],
    "Ranno": [
        "Default",
        "Abyss",
        "Blue",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "Infamous",
        "Pink",
        "Pool Party",
        "Ranked",
        "Red",
        "Summer",
        "Tuxedo",
        "Valentines"
    ],
    "ShovelKnight": [
        "Default",
        "Abyss",
        "Champion",
        "Christmas",
        "Cyan",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "Infamous",
        "Purple",
        "Ranked",
        "Red",
        "Summer",
        "Valentines"
    ],
    "Sylvanos": [
        "Default",
        "Abyss",
        "Blue",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Genesis",
        "Golden",
        "Green",
        "Halloween",
        "Infamous",
        "Purple",
        "Ranked",
        "Red",
        "Steampunk",
        "Summer",
        "Valentines",
        "White"
    ],
    "Wrastor": [
        "Default",
        "Abyss",
        "Blue",
        "Bradshaw",
        "Champion",
        "Christmas",
        "Collegiate",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "Purple",
        "Ranked",
        "Red",
        "Spangled",
        "Summer",
        "Valentines"
    ],
    "Zetterburn": [
        "Default",
        "Abyss",
        "Blue",
        "Champion",
        "Christmas",
        "Default Custom 1",
        "Default Custom 2",
        "Early Access",
        "Excaliburn",
        "Golden",
        "Green",
        "Grey",
        "Halloween",
        "LoA",
        "Purple",
        "Ranked",
        "Red",
        "Shine",
        "Steampunk",
        "Summer",
        "Valentines"
    ]
};