export let ssb64 = {
    "Bowser": ["Default", "Black", "Blue", "Green", "Red", "Yellow"],
    "Conker": ["Default", "Black", "Green", "Pink", "Red", "White"],
    "Dark Samus": ["Default", "Brown", "Gray", "Power", "Purple", "White"],
    "DonkeyKong": ["Default", "Black", "Blue", "Green", "Pink", "Red", "White", "Yellow"],
    "Dr. Mario": ["Default", "Black", "Blue", "Green", "Pink", "Yellow"],
    "Falco": ["Default", "Gray", "Green", "Red", "White", "Yellow"],
    "Falcon": ["Default", "Black", "Blood", "Blue", "Gold", "Green", "Pink", "Red"],
    "Fox": ["Default", "Black", "Blue", "Green", "Orange", "Purple"],
    "Ganondorf": ["Default", "Blue Skin", "Green", "Purple Skin", "Purple", "Red"],
    "Jigglypuff": ["Default", "Blue", "Green Bow Light Skin", "Green", "Monochrome", "Purple", "Red", "Yellow"],
    "King Dedede": ["Default", "Black", "Blue", "Brown", "Green", "Purple"],
    "Kirby": ["Default", "Blue", "Green", "Meta Knight", "Monochrome", "Red", "Yellow"],
    "Link": ["Default", "Black", "Blue", "Red", "White", "Yellow"],
    "Lucas": ["Default", "Brown Shorts", "Claus", "Green Shorts", "Kumatora", "Pink Shorts"],
    "Luigi": ["Default", "Blue", "Fire", "Pink", "Super Show", "Waluigi"],
    "Marina": ["Default", "Blue", "Green", "Purple", "Red", "Yellow"],
    "Mario": ["Default", "Blue", "Brown", "Classic", "Fire", "Green", "Wario"],
    "Marth": ["Default", "Black", "Gold", "Green", "Red", "White"],
    "Mewtwo": ["Default", "Blue", "Cyan", "Green", "Red", "Yellow"],
    "Ness": ["Default", "Blue", "Green", "Purple", "White", "Yellow"],
    "Pikachu": ["Default", "All Green", "Blue", "Green", "Purple", "Red", "Yellow"],
    "Samus": ["Default", "Black", "Green", "Pink", "Power", "Purple", "White"],
    "Sheik": ["Default", "Black", "Green", "Purple", "Red Blue", "Red"],
    "Sonic": ["Default", "Black", "Green", "Purple", "Red", "Yellow", "Classic Default", "Classic Green", "Classic Orange", "Classic Pink", "Classic Red", "Classic Yellow"],
    "Wario": ["Default", "Blue", "Green", "Mario", "Purple", "Yellow"],
    "Wolf": ["Default", "Black", "Blue", "Green", "Pink", "Purple"],
    "Yoshi": ["Default", "Black", "Blue", "Dark Blue", "Pink", "Red", "White", "Yellow"],
    "Young Link": ["Default", "Blue", "Cyan", "Dark", "Pink Hair", "Red"],
};

export let ssbm = {
    'Bowser': ['Default', 'Black', 'Blue', 'Red'], 
    'DonkeyKong': ['Default', 'Black', 'Blue', 'Green', 'Red'], 
    'DrMario': ['Default', 'Black', 'Blue', 'Green', 'Red'], 
    'Falco': ['Default', 'Green', 'Red', 'White'], 
    'Falcon': ['Default', 'Black', 'Blood', 'Blue', 'Green', 'Pink'], 
    'Fox': ['Default', 'Blue', 'Green', 'Orange'], 
    'Ganondorf': ['Default', 'Blue', 'Green', 'Purple', 'Red'], 
    'IceClimbers': ['Default', 'Green', 'Nana Orange', 'Nana Purple'], 
    'Jigglypuff': ['Default', 'Blue', 'Crown', 'Green', 'Red'], 
    'Kirby': ['Default', 'Blue', 'Green', 'Red', 'White', 'Yellow'], 
    'Link': ['Default', 'Black', 'Blue', 'Red', 'White'], 
    'Luigi': ['Default', 'Blue', 'Fire', 'Pink'], 
    'Mario': ['Default', 'Black', 'Blue', 'Green', 'Wario'], 
    'Marth': ['Default', 'Black', 'Green', 'Red', 'White'], 
    'Mewtwo': ['Default', 'Blue', 'Green', 'Red'], 
    'MrGameAndWatch': ['Default', 'Blue', 'Green', 'Red'], 
    'Ness': ['Default', 'Blue', 'Green', 'Yellow'], 
    'Peach': ['Default', 'Blue', 'Daisy', 'Green', 'White'], 
    'Pichu': ['Default', 'Blue', 'Green', 'Red'], 
    'Pikachu': ['Default', 'Blue', 'Green', 'Red'], 
    'Roy': ['Default', 'Blue', 'Green', 'Orange', 'Red'], 
    'Samus': ['Default', 'Black', 'Green', 'Pink', 'Purple'], 
    'Sheik': ['Default', 'Black', 'Blue', 'Green', 'Red'], 
    'Yoshi': ['Default', 'Cyan', 'Dark Blue', 'Pink', 'Red', 'Yellow'], 
    'YoungLink': ['Default', 'Black', 'Blue', 'Red', 'White'], 
    'Zelda': ['Default', 'Blue', 'Green', 'Red', 'White']
};